Adding MemoryGame class with basic properties and methods
ledezmam/js-dev-fnd-05 pull request #1
Opened 2016-09-19 02:34 UTC by 6chelo6

2016-09-19 20:33 UTC, ledezmam commented on tasks/memory-game/group-Row1/src/MemoryGame.js
> +MemoryGame.prototype.setArray = function () {
No hay necesidad de setear el array como tal con X, podriamos tener solo una  funcion q se llame DisplayBoard donde se hara el control interno de que tenemos que desplegar

2016-09-19 20:35 UTC, ledezmam commented on tasks/memory-game/group-Row1/src/MemoryGame.js
> +	this.x = size;
no parece necesario tener x y y...

2016-09-19 20:37 UTC, ledezmam commented on tasks/memory-game/group-Row1/src/MemoryGame.js
> +	for (var i = 0; i < this.x; i++){
en vez de this.x, directamente podriamos tener this.size

2016-09-19 20:37 UTC, ledezmam commented on tasks/memory-game/group-Row1/src/MemoryGame.js
> +		for (var j = 0; j < this.y; j++) {
en vez de this.x, directamente podriamos tener this.size

2016-09-19 20:38 UTC, ledezmam requested changes
Por favor revisa los comentarios agregados a este PR

2016-09-19 20:43 UTC, 6chelo6 commented on tasks/memory-game/group-Row1/src/MemoryGame.js
> +	for (var i = 0; i < this.x; i++){
This was thought to have a new version in the future to have a rectangle instead a square ;-)

2016-09-20 01:49 UTC, ledezmam approved these changes
based on disscussion, will be working on refactoring based on this code

2016-09-20 01:50 UTC, merged